/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialogdemo: typeof import('./components/dialogdemo.vue')['default']
    NekoDialog: typeof import('./components/NekoDialog.vue')['default']
    NekoFrame: typeof import('./components/NekoFrame.vue')['default']
    'NekoFrame未拆分': typeof import('./components/NekoFrame未拆分.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
