/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/NekoFrame copy.vue')['default']
    DeleteButton: typeof import('./components/DeleteButton.vue')['default']
    Footer: typeof import('./components/footer.vue')['default']
    NekoFab: typeof import('./components/NekoFab.vue')['default']
    NekoFooter: typeof import('./components/NekoFooter.vue')['default']
    NekoFrame: typeof import('./components/NekoFrame.vue')['default']
    'NekoFrame无自定义API版': typeof import('./components/NekoFrame无自定义API版.vue')['default']
    NekoSpeed: typeof import('./components/NekoSpeed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Speed: typeof import('./components/speed.vue')['default']
  }
}
